import "~/styles/globals.css";

// eslint-disable-next-line import/no-unresolved
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import type React from "react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default ({ children }: Readonly<{ children: React.ReactNode }>) => (
  <html lang="en" className={`${GeistSans.variable}`}>
    <body>{children}</body>
  </html>
);
