import "~/styles/globals.css";
// eslint-disable-next-line import/no-unresolved
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import React from "react";
import { JetBrains_Mono } from '@next/font/google'

const jetBrainsMono = JetBrains_Mono({
  subsets: ['latin', 'cyrillic'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
  variable: '--font-jbm',
})
export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default ({
  children,
}: Readonly<{ children: React.ReactNode }>) => (
  <html lang="en" className={`${jetBrainsMono.variable} font-sans`}>
    <body>{children}</body>
  </html>
)
